#!/usr/bin/with-contenv bash

# main process
if [ -z ${TEST_RUN+x} ]; then \
	s6-setuidgid abc /usr/bin/zmpkg.pl start
fi

# pid monitoring
while true ; do
	if [ -f "/var/run/zoneminder/zm.pid" ]; then
		if kill -s 0 $(cat /var/run/zoneminder/zm.pid); then
			sleep 5
		else
			exit 1
		fi
	else
		sleep 5
		exit 1
	fi
done
