#!/usr/bin/with-contenv bash

# make folders if required
mkdir -p \
	"$DATADIR" \
	/config{/apache,/keys,/log/apache,/log/mysql,/log/zoneminder,/zoneminder} \
	/data{zoneminder/events,/zoneminder/exports,/zoneminder/images,/zoneminder/sounds} \
	/var/run/mysqld \
	/var/run/zoneminder

# setup custom cnf file
[[ ! -f /config/custom.cnf ]] && \
	cp /defaults/my.cnf /config/custom.cnf
[[ ! -L /etc/mysql/conf.d/custom.cnf && -f /etc/mysql/conf.d/custom.cnf ]] && \
	rm /etc/mysql/conf.d/custom.cnf
[[ ! -L /etc/mysql/conf.d/custom.cnf ]] && \
	ln -s /config/custom.cnf /etc/mysql/conf.d/custom.cnf

# set permissions
if [ -e /etc/mysql/debian.cnf ] ; then
	chown abc:abc /etc/mysql/debian.cnf
	chmod 644 /etc/mysql/debian.cnf
fi
chmod -R 777 \
	/var/lib/apache2 \
	/var/run/mysqld \
	/var/run/zoneminder
