#!/usr/bin/with-contenv bash

# Env variable validation
VARS=( \
DB_HOST \
DB_USER \
DB_PASS 
)
for i in "${VARS[@]}"; do
	if [ -z ${!i+x} ]; then
		echo "[cont-init.d] ${i} is required and is not set will not continue"
		exit 0
	fi
done

# create directories
mkdir -p \
	/config/log/zoneminder \
	/config/zoneminder/{cache,events,images,temp} \
	/var/run/zoneminder

# symlinks
[[ ! -L "/var/lib/zoneminder" ]] && \
	rm -Rf "/var/lib/zoneminder" && \
	ln -s /config/zoneminder /var/lib/zoneminder
[[ ! -L "/var/cache/zoneminder" ]] && \
        rm -Rf "/var/cache/zoneminder" && \
        ln -s /config/zoneminder/cache /var/cache/zoneminder
LOGFILES=( \
/var/log/zoneminder/zmdc.log \
/var/log/zoneminder/zmpkg.log
)
for LOGFILE in "${LOGFILES[@]}"; do
	[[ -e "${LOGFILE}" && ! -L "${LOGFILE}" ]] && rm -f "${LOGFILE}"
	[[ ! -L "${LOGFILE}" ]] && ln -s /config/log/zoneminder/"$(basename ${LOGFILE})" "${LOGFILE}"
	touch /config/log/zoneminder/"$(basename ${LOGFILE})"
done
CONFIGFILE="/etc/zm.conf"
[[ ! -e "/config/$(basename ${CONFIGFILE})" ]] && \
	cp /defaults/"$(basename ${CONFIGFILE})" /config/"$(basename ${CONFIGFILE})" && \
	sed -i \
		-e "s/REPLACE_DB_HOST/${DB_HOST}/g" \
	        -e "s/REPLACE_DB_USER/${DB_USER}/g" \
	        -e "s/REPLACE_DB_PASS/${DB_PASS}/g" \
		/config/"$(basename ${CONFIGFILE})"	
[[ -e "${CONFIGFILE}" && ! -L "${CONFIGFILE}" ]] && rm -f "${CONFIGFILE}"
[[ ! -L "${CONFIGFILE}" ]] && ln -s /config/"$(basename ${CONFIGFILE})" "${CONFIGFILE}"

# check for the mysql endpoint for 30 seconds
END=$((SECONDS+30))
while [ ${SECONDS} -lt ${END} ]; do
	/usr/bin/nc -z ${DB_HOST} 3306 && \
	if [ ! -z "$(/usr/bin/nc -w1 ${DB_HOST} 3306)" ]; then
		[ ! -z "${RUN}" ] && break
		RUN="RAN"
		# we sleep here again due to first run init on DB containers
		[ ! -f /dbwait.lock ] && sleep 5
	else
		sleep 1
	fi
	sleep 1
done

# run initial database sync if table does not exist
if ! mysql -h "${DB_HOST}" -u"${DB_USER}" -p"${DB_PASS}" zm -e"SELECT 1 FROM Config LIMIT 1;"; then
	mysql -h "${DB_HOST}" -u"${DB_USER}" -p"${DB_PASS}" < /usr/share/zoneminder/db/zm_create.sql
	mysql -h "${DB_HOST}" -u"${DB_USER}" -p"${DB_PASS}" zm -e "UPDATE Storage set Path='/data' where Id=1;"
fi

# permissions
chown -R abc:abc \
	/config \
	/var/log/zoneminder \
	/var/run/zoneminder
chown abc:abc /data
